# Set the base image to ubuntu
FROM ubuntu:14.04

# Install Node.js & other dependencies
RUN mkdir -p /var/log/supervisor && \ 
		mkdir -p /logs && \
		mkdir -p /tempNode && \
		mkdir -p /opt

ADD package.json /tempNode/package.json
RUN apt-get update

RUN	apt-get -y install curl sudo && \
		curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash - && \
		apt-get -y install python make nodejs && \
		apt-get -y install 	ca-certificates nginx gettext-base && \
		npm install -g node-gyp && \
		node-gyp clean && \
		ln -sf /dev/stdout /var/log/nginx/access.log && \
		ln -sf /dev/stderr /var/log/nginx/error.log && \
		cd /tempNode && \
		rm -rf node_modules && \
		npm install && \
		npm install -g webpack
